# Generated by Django 5.1.4 on 2024-12-31 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velvetekapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
                ('contact_number', models.CharField(max_length=15, null=True)),
                ('whatsapp_number', models.CharField(max_length=15, null=True)),
                ('reffered_by', models.CharField(max_length=255, null=True)),
                ('work_type', models.CharField(choices=[('sale', 'sale'), ('service', 'service')], default='sale', max_length=10)),
                ('item_name_or_number', models.CharField(max_length=255, null=True)),
                ('issue', models.TextField(blank=True, null=True)),
                ('estimation_document', models.FileField(blank=True, null=True, upload_to='apply')),
                ('estimated_price', models.CharField(max_length=255)),
                ('estimated_date', models.DateField(null=True)),
                ('any_other_comments', models.CharField(blank=True, max_length=255, null=True)),
                ('service_by', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apply/images')),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_of_item', to='velvetekapp.apply')),
            ],
        ),
    ]
