# Generated by Django 5.1.4 on 2024-12-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velvetekapp', '0002_apply_applyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='reffered_by',
            field=models.CharField(max_length=255),
        ),
    ]
