# Generated by Django 5.1.4 on 2025-01-01 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velvetekapp', '0004_apply_photos_of_item_alter_apply_work_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='service_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apply',
            name='work_type',
            field=models.CharField(choices=[('sale', 'sale'), ('service', 'service')], default='sale', max_length=10),
        ),
    ]
