# Generated by Django 5.1.4 on 2025-01-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velvetekapp', '0005_alter_apply_service_by_alter_apply_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='estimation_document',
            field=models.FileField(upload_to='apply'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='photos_of_item',
            field=models.ImageField(upload_to='apply'),
        ),
    ]
