# Generated by Django 5.1.4 on 2025-01-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velvetekapp', '0006_alter_apply_estimation_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='estimation_document',
            field=models.FileField(upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='photos_of_item',
            field=models.ImageField(upload_to='images'),
        ),
    ]
