# Generated by Django 5.1.4 on 2025-01-15 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velvetekapp', '0007_alter_apply_estimation_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='velvetekapp.customer'),
        ),
    ]
