# Generated by Django 5.1.4 on 2025-01-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velvetekapp', '0008_apply_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='estimation_document',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='photos_of_item',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
