# Generated by Django 5.1.4 on 2025-01-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velvetekapp', '0009_alter_apply_estimation_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='reffered_by',
            new_name='referred_by',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='reffered_by',
            new_name='referred_by',
        ),
    ]
