# Generated by Django 3.1.12 on 2025-02-05 08:21

from django.db import migrations, models

import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('velvetekapp', '0010_rename_reffered_by_apply_referred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        
        migrations.AlterField(
            model_name='apply',
            name='photos_of_item',
            field=models.TextField(blank=True, null=True),
        ),
    ]
