# Generated by Django 3.1.12 on 2025-02-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velvetekapp', '0011_auto_20250202_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='apply',
            name='created_month',
            field=models.IntegerField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply',
            name='created_year',
            field=models.IntegerField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
