# Generated by Django 5.1.4 on 2025-02-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velvetekapp', '0011_auto_20250205_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Assigned', 'Assigned')], default='Assigned', max_length=50),
        ),
    ]
