# Generated by Django 5.1.4 on 2025-02-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velvetekapp', '0012_apply_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='contact_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
