# Generated by Django 3.1.12 on 2025-02-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velvetekapp', '0012_auto_20250205_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
