# Generated by Django 5.1.4 on 2025-02-14 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velvetekapp', '0013_alter_apply_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly 10 digits and contain only numbers.', regex='^\\d{10}$')]),
        ),
    ]
