# Generated by Django 3.1.12 on 2025-02-05 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('velvetekapp', '0015_auto_20250205_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='created_month',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='created_year',
        ),
        migrations.AlterField(
            model_name='apply',
            name='created_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
