# Generated by Django 5.1.6 on 2025-02-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velvetekapp', '0016_alter_apply_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='estimated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='estimated_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='referred_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
