# Generated by Django 3.1.12 on 2025-02-05 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('velvetekapp', '0016_auto_20250205_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
