# Generated by Django 5.1.6 on 2025-02-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velvetekapp', '0017_alter_apply_address_alter_apply_estimated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='referred_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='whatsapp_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
