# Generated by Django 3.1.12 on 2025-02-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velvetekapp', '0017_auto_20250205_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='photos_of_item',
            field=models.TextField(blank=True, null=True),
        ),
    ]
