# Generated by Django 5.1.4 on 2025-01-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('technician', 'Technician'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
