# Generated by Django 5.1.4 on 2025-01-06 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicianapp', '0002_foodallowance'),
        ('velvetekapp', '0007_alter_apply_estimation_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPurchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_photo', models.ImageField(upload_to='itempurchased')),
                ('customer_name', models.CharField(max_length=225)),
                ('issue', models.TextField()),
                ('apply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itempurchased', to='velvetekapp.apply')),
            ],
        ),
    ]
