# Generated by Django 5.1.4 on 2025-01-06 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicianapp', '0003_itempurchased'),
        ('velvetekapp', '0007_alter_apply_estimation_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_bill_photo', models.ImageField(upload_to='vendorinfo')),
                ('vendor_eta', models.DateField()),
                ('vendor_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_name', models.CharField(max_length=225)),
                ('issue', models.TextField()),
                ('apply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='velvetekapp.apply')),
            ],
        ),
    ]
