# Generated by Django 5.1.4 on 2025-01-06 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicianapp', '0004_vendorinfo'),
        ('velvetekapp', '0007_alter_apply_estimation_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('technician_name', models.CharField(max_length=100)),
                ('status', models.TextField()),
                ('customer_name', models.CharField(max_length=225)),
                ('issue', models.TextField()),
                ('apply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_status_entries', to='velvetekapp.apply')),
            ],
        ),
    ]
