# Generated by Django 5.1.4 on 2025-01-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicianapp', '0005_currentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentstatus',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Assigned', 'Assigned')], default='Assigned', max_length=50),
        ),
    ]
