# Generated by Django 5.1.4 on 2025-02-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicianapp', '0008_alter_currentstatus_id_alter_foodallowance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodallowance',
            name='review',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fuelcharge',
            name='review',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itempurchased',
            name='review',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorinfo',
            name='review',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
